fail harder

diff --git a/.github/workflows/serverless_pr.yaml b/.github/workflows/serverless_pr.yaml
--- a/.github/workflows/serverless_pr.yaml
+++ b/.github/workflows/serverless_pr.yaml
@@ -16,6 +16,7 @@ jobs:
         id: filter
         uses: dorny/paths-filter@v2
         with:
+          list-files: shell
           filters: |
             log:
               - 'log/**'
@@ -25,7 +26,10 @@ jobs:
       - name: Detect log structure changes
         if: steps.filter.outputs.log == 'true' && steps.filter.outputs.pending == 'false'
         run: |
-          echo "::error:PR modifies protected log structure - ensure additions are placed in the .../leaves/pending directory"
+          for i in ${{ steps.filter.outputs.log_files }}; do
+                  echo "::error: file=${i} Modified protected log structure - ensure additions are placed in the .../leaves/pending directory"
+          done
+          exit 1
 
 # Run this job only when we've detected pending leaf additions
   leaf_validator_job:
